### ISSUE TITLE
What are bcite icons for?

### ISSUE THREAD

**Issue by jbotelho2-bb** [bloombergbna/fishtank-icons#9]
## Expected Behavior
I expected that all the icons in this library would be generic, but it seems there's some icons and/or terminology specific to Bloomberg Law in here.

Looking specifically at icons like: [bcite-caution](https://github.com/bloombergbna/fishtank-icons/blob/master/src/bcite-caution_24.svg)

**Comment by bakpa79** [comment]
Fish Tank icons is the sole provider of icons across BBNA brands. To support centralization and scale, we are collecting together in one repo.

**Comment by jbotelho2-bb** [comment]
That's fine, but then why are they open source? Typically the purpose of open-sourcing is to expose code or content that would be of use to developers outside the organization. As an external user I'd find the mix of generic and proprietary icons confusing.

**Comment by jmai14** [comment]
Hey JBot.  Our primary support is to BNA products, which across the range of them, they have a wide range of technology stacks.  Many of which may access via public npm.  So while maybe not the BCITE icons specifically, other BNA products will use the open source icons.  And we're not going to the effort to create both a public and non-public version of our repos, or BLAW vs. BGOV versions of the repos.  So yeah, there will be some brand specific things in there that other BNA products or the broader open source community will find little value in.  But thats ok.
